### ISSUE TITLE
Baby woc and Dispenser bot files

### ISSUE THREAD

**Issue by 2milker0** [trbodev/smleaks#7]
![image](https://user-images.githubusercontent.com/95142111/143690941-943e697b-ccbb-4bc6-b114-0d7d1bad23e6.png)
steam/steamapps/common/Scrap Mechanic/Survival/Character
Unsure of what the Char_dispenserbot is and unable to Render it so i cant provide you with more info or renders
as for Char_Babycow i assume it to be an npc teased in Devblog 22

**Comment by trbodev** [comment]
um, do you have any mods installed because `Char_BabyCow` doesn't exist in the base game.

**Comment by trbodev** [comment]
also `Char_dispenserbot` is the bot that well "dispenses" new bots at the mechanic station
