### ISSUE TITLE
PINK TAPE DECK ANYONE KNOW ABOUT THIS

### ISSUE THREAD

**Issue by NeonVX** [trbodev/smleaks#8]
**Describe the leaked content**
It's something to do with the log book it is a pink tape deck
**Where is it located?**
C:\Program Files (x86)\Steam\steamapps\common\Scrap Mechanic\Data\Gui\Resolutions\1920x1080\Logbook

**Screenshots/Media**
[](https://cdn.discordapp.com/attachments/858828510592630815/920899583108853850/unknown.png
)
**Additional context**
nope

**Comment by trbodev** [comment]
sorry to inform you but this is already know and is also up on the website.  https://smleaks.com/logbook/items
